eureka:
     client:
         serviceUrl:
             defaultZone: http://localhost:9090/eureka/
server:
     port: 8904
spring:
     application:
         name: bbs-zuul-service
zuul:
     routes:
         ribbo:
               path: /api-r/**
               serviceId: bbs-ribbon
#         feign:
#               path: /api-f/**
#               serviceId: service-feign