server:
  port: 8080
spring:
  application:
    name: bbs-ribbon
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
  instance:
    hostname: ribbon
ribbon:
  eureka:
    enabled: true
info:
  app:
    name: ribbon
    description: description
    version:  version